### ISSUE TITLE
Any plans for null-safety?

### ISSUE THREAD

**Issue by woogi-kang** [redsolver/skynet#1]
Hello, thanks for this library! 

Is there any plans for migrating this library to null-safety? I really look forward for this! 

Thank you

**Comment by redsolver** [comment]
The library is now migrated to null-safety, you can try it using
```yaml
dependencies:
  skynet:
    git: https://github.com/redsolver/skynet.git
```
